#!/usr/bin/python3
import sys
import ctypes
from unix_time import unix_time
from find_factor import find_factor
def main():
    lenght = len(sys.argv)
    if lenght < 2:
        print("USAGE: ./factor <file_name>")

    else:
        file_path = sys.argv[1]
        file = open(file_path, 'r')
        
        for line in file:
            line = line.strip()
            number = int(line)
            factor = ctypes.CDLL("./libfind_factor.so")
            factor.smallest_divisor.argtypes = [ctypes.c_long]
            factor.smallest_divisor(number)

            print(f"{number}={number // factor.smallest_divisor(number)}*{factor.smallest_divisor(number)}")


if __name__ == "__main__":
    unix_time(main)
